#include<stdio.h>
int main(){
    char ch;
    FILE *fp;
    if((fp=fopen("//Users//ashish//Desktop//structure//filemani//filemani//data.txt","r+"))==NULL){ // it will open the exesting file if there is not any existing file then it will print Error! then program stops...
        printf("Error!");
        return -1;  // the program return false then exited..
    }
    fseek(fp,0,SEEK_END);   // it will point the initial position first position on the file to write...
    scanf("%c",&ch);  //it will ask the chracter input to the user then.....
    // file operation starts from here.......
    fwrite(&ch,sizeof(char),1,fp); // it will write on the file the input given from the scanf....
    fseek(fp,-2,SEEK_CUR); // it will return the pointer to the first position in the file....
    fwrite(&ch,sizeof(char),1,fp);  // then it will write on the file...
    fclose(fp);
    return 0;
}
